title: Views
modelClass: Mavitm\Staff\Models\Property
list: $/mavitm/staff/models/property/view_columns.yaml
recordUrl: 'mavitm/staff/views/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '100'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
